"use server";

import { revalidatePath } from "next/cache";

import { calcTax } from "@/lib/money";
import { requireRole } from "@/lib/auth/guard";
import { createClient } from "@/lib/supabase/server";
import { purchaseOrderSchema } from "./_lib/schema";
import type { PurchaseOrderRow, PurchaseOrderInput } from "./_lib/schema";

// ponytail: doc_no generated by DB default (PO-YYYY-NNNN).
// ponytail: money math in satang (integer cents) per AGENTS.md.

const SUP = (n: number) => Math.round(n * 100);
const UNSUP = (cents: number) => cents / 100;

export async function getPurchaseOrders(): Promise<PurchaseOrderRow[]> {
  const supabase = await createClient();
  const { data, error } = await supabase
    .from("purchase_orders")
    .select("id, doc_no, supplier_id, suppliers!inner(name), status, order_date, expected_date, tax_mode, vat_rate, subtotal, vat_amount, grand_total, note, created_at")
    .order("created_at", { ascending: false });
  if (error) throw new Error(error.message);
  return (data ?? []).map((r) => ({
    id: r.id,
    doc_no: r.doc_no,
    supplier_id: r.supplier_id,
    supplier_name: r.suppliers?.name ?? null,
    status: r.status,
    order_date: r.order_date,
    expected_date: r.expected_date ?? null,
    tax_mode: r.tax_mode,
    vat_rate: r.vat_rate,
    subtotal: r.subtotal,
    vat_amount: r.vat_amount,
    grand_total: r.grand_total,
    note: r.note ?? null,
    created_at: r.created_at,
  })) as PurchaseOrderRow[];
}

export async function getPurchaseOrder(id: string) {
  const supabase = await createClient();
  const { data: po, error: poError } = await supabase
    .from("purchase_orders")
    .select("*")
    .eq("id", id)
    .maybeSingle();
  if (poError) throw new Error(poError.message);
  const { data: items, error: itemsError } = await supabase
    .from("purchase_order_items")
    .select("id, product_id, products!inner(sku, name_th), qty_ordered, qty_received, unit_cost")
    .eq("purchase_order_id", id)
    .order("id");
  if (itemsError) throw new Error(itemsError.message);
  return {
    ...po,
    items: (items ?? []).map((i) => ({
      id: i.id,
      product_id: i.product_id,
      product_sku: i.products?.sku ?? null,
      product_name: i.products?.name_th ?? null,
      qty_ordered: i.qty_ordered,
      qty_received: i.qty_received,
      unit_cost: i.unit_cost,
    })),
  };
}

export async function upsertPurchaseOrder(input: PurchaseOrderInput, id?: string | null) {
  const parsed = purchaseOrderSchema.safeParse(input);
  if (!parsed.success) return { ok: false as const, error: "Invalid input" };
  await requireRole(["owner", "manager"]);
  const supabase = await createClient();

  const subtotalCents = parsed.data.items.reduce((sum, i) => sum + SUP(i.unit_cost) * i.qty_ordered, 0);
  const { base, vat } = calcTax(UNSUP(subtotalCents + SUP(parsed.data.shipping_cost ?? 0) + SUP(parsed.data.other_cost ?? 0)), parsed.data.tax_mode as "none" | "exclusive" | "inclusive", parsed.data.vat_rate ?? 7);
  const grandTotalCents = SUP(base) + SUP(vat);

const poPayload: Record<string, unknown> = {
    ...(id ? { id } : {}),
    supplier_id: parsed.data.supplier_id,
    expected_date: parsed.data.expected_date ?? null,
    tax_mode: parsed.data.tax_mode,
    vat_rate: parsed.data.vat_rate ?? 7,
    shipping_cost: parsed.data.shipping_cost ?? 0,
    other_cost: parsed.data.other_cost ?? 0,
    subtotal: UNSUP(subtotalCents),
    vat_amount: UNSUP(SUP(vat)),
    grand_total: UNSUP(grandTotalCents),
    note: parsed.data.note ?? null,
  };

  const { data: upserted, error: poError } = await supabase.from("purchase_orders").upsert(poPayload as never, { onConflict: id ? "id" : undefined }).select("id").maybeSingle();
  if (poError) return { ok: false as const, error: poError.message };

  const resolvedId = upserted?.id ?? id;
  // sync line items (full replace)
  if (resolvedId) {
    const { error: delErr } = await supabase.from("purchase_order_items").delete().eq("purchase_order_id", resolvedId);
    if (delErr) return { ok: false as const, error: delErr.message };
    const itemRows = parsed.data.items.map((i) => ({
      purchase_order_id: resolvedId,
      product_id: i.product_id,
      qty_ordered: i.qty_ordered,
      unit_cost: UNSUP(SUP(i.unit_cost)),
    }));
    const { error: insErr } = await supabase.from("purchase_order_items").insert(itemRows);
    if (insErr) return { ok: false as const, error: insErr.message };
  }

  revalidatePath("/dashboard/purchase-orders");
  if (resolvedId) revalidatePath(`/dashboard/purchase-orders/${resolvedId}`);
  return { ok: true as const, id: resolvedId };
}

export async function deletePurchaseOrder(id: string) {
  await requireRole(["owner", "manager"]);
  const supabase = await createClient();
  const { error } = await supabase.from("purchase_orders").delete().eq("id", id);
  if (error) return { ok: false as const, error: error.message };
  revalidatePath("/dashboard/purchase-orders");
  return { ok: true as const };
}
